[package]
name = "markdown-tools"
version = "0.1.0"
edition = "2024"

[dependencies]
itertools = "0.14.0"
pulldown-cmark = "0.13.0"
similar = "2.7.0"

[dev-dependencies]
insta = { version = "1.43.1", features = ["yaml"] }
