[package]
name = "markdown-tools"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.48", features = ["derive"] }
itertools = "0.14.0"
nonempty = "0.12.0"
percent-encoding = "2.3.2"
ptree = "0.5.2"
pulldown-cmark = "0.13.0"
similar = "2.7.0"
tree-sitter = "0.25.9"

[dev-dependencies]
insta = { version = "1.43.1", features = ["yaml"] }
